### ISSUE TITLE
Not available in the Plugin Portal

### ISSUE THREAD

**Issue by sgoings** [ReadyTalk/gradle-readytalk-ci#1]
FAILURE: Build failed with an exception.
- Where:
  Build file '/home/sgoings/readytalk/avian/build.gradle' line: 12
- What went wrong:
  Plugin [id: 'com.readytalk.ci', version: '0.1.0'] not found in plugin repositories:
  - Gradle Distribution Plugins (listing: http://gradle.org/docs/2.0/userguide/standard_plugins.html)
  - Plugin Portal (http://plugins.gradle.org)
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.636 secs

**Comment by stormbeta** [comment]
0.2.0 is available via the plugin portal now.
